name: UI tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Start test server
        run: |
          cd dist
          python3 -m http.server 8000 &
          sleep 5

      - name: Run tests
        env:
          # иногда нужно указать путь к Chrome, но setup-chrome обычно сам добавляет в PATH
          # CHROME_BIN: /usr/bin/google-chrome
        run: |
          pytest -v